### ISSUE TITLE
🛎️ The Reception

### ISSUE THREAD

**Issue by axel-eck** [epitech-mirroring/Plazza#1]
# 👮‍♂️ What's needed
We need to create a reception that will take our orders and dispatch them among kitchens.
The reception is also in charge of creating kitchen

## 📋 Subtasks
- [x] Read program args
- [x] Handle input buffer them and wait for CTRL+D or CTRL+C
- [x] Create kitchen
- [x] Dispatch commands and notify user when pizzas are ready

# 📜 Sources
[B-CCP-400_plazza.pdf (Only receptions pages)](https://github.com/epitech-mirroring/Plazza/files/15305178/B-CCP-400_plazza.1.pdf)
